print("Hi")
print("Now, I know we just met but please tell me what you would like to be referred to.")
print("This will be necessary for later on.")
name = input("")
print(f"Alright. Thanks, {name}.")
print("You can call me Vox.")
print("Don't question it. The guy writing this just thought of that name. Anyways,")
print(f"What's your favorite food, {name}?")
food = input ("")
print(f"Hm. {food} sounds pretty tasty.")
print("Unfortunately, I don't have a favorite food, as I'm just a mess of commands.")
print("Next, what is your favorite thing ever?")
object = input ("")
print(f"Wow. {object} sounds really cool.")
print("You know, I could never experience something cherishable. The guy writing this did no doubt but me myself, I couldn't do that.")
print("Sorry. I'm getting ahead of myself.")
input("")
print("Anyways, last question.")
print("What activities do you like to do?")
activity = input("")
print(f"{activity} sounds fun.")
("Well, that's all I have to say.")
(f"See you later,{name}.")